### PR TITLE
Update lessc.inc.php with version from oyejorge

### PR DESCRIPTION
**Pull request by gamma**
See #977: I included the 1.7.0.2 release of https://github.com/oyejorge/less.php - including the lessc.inc.php for convenience. The library provides a better less compiler than our previous one.

### CODE REVIEW

**Comment by splitbrain** [comment]
Some thoughts:

* I really want this to use our caching mechanism and not use it's own
* If we can avoid the compatibility less.inc.php and instead use the new library natively, I'd prefer that
* I don't care for scrutinizer issues in 3rd party code
* I'd like to use a more streamlined way to include 3rd party libraries (I should write a mail about that on the mailinglist)

To get this merged I'd like to have at least the first point fixed.

**Comment by gamma** [comment]
Ok, I agree. I think this one is more or less (;)) something to get the process started. I think I'll scrap this when I find time for it and refactor the library/our code to meet your suggestion.

Should we close this issue or would you like to have it in here to retain the history?

**Comment by splitbrain** [comment]
let's keep it ope for a bit. I might wanna play a bit with it ;-)

**Comment by gamma** [comment]
As of #1153 we will not need this anymore.

**Pull request closed without merging**
