### PR TITLE
new wildcard %NAME% for ACL rules

### PR DESCRIPTION
**Pull request by juliusverrel**
Introduces a new wildcard %NAME%, to be replaced by user's full name (after applying ``cleanID``). This is needed in a context where the existing wildcard %USER% cannot be used for data protection reasons (%USER% = student matriculation number)

### CODE REVIEW

**Comment by splitbrain** [comment]
That's a terrible idea. User's names are not unique and can be changed by users themselves. Basing ACLs on it makes no sense. I also do not understand what this has to do with data protection. If matriculation numbers are somehow worth to be protected you should not use them as user names in the first place.

**Comment by phy25** [comment]
Anyway this can probably be done via a plugin, if you still want to implement such an ACL rule.

**Comment by juliusverrel** [comment]
Thanks, I agree it's terrible - unfortunately I can't simply change it because the wiki is maintained by university IT...

**Comment by peterfromearth** [comment]
If you make a plugin you can use hashed (and salted) %USER% ID

**Pull request closed without merging**
