### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by Dr-Yukon**
Code slightly minified

### CODE REVIEW

**Comment by splitbrain** [comment]
what's the motivation here?

**Comment by phy25** [comment]
Looks good, at least one less directory read? (I guess `glob` doesn't have a cache there)

**Comment by Dr-Yukon** [comment]
right
> at least one less directory read
but main motivation is "по фэн-шую" :D i mean this code is more beauty

**Comment by splitbrain** [comment]
squashed as cf847c250d0d3e5c395dda99a9e595af0d7bb456

**Pull request closed without merging**
