### PR TITLE
Translation update (oc)

### PR DESCRIPTION
**Pull request by dokuwiki-translate**
This pull request contains some translation updates.

### CODE REVIEW

**Comment by phy25** [comment]
Wow, this is a language that I have never heard about. Do we just accept this whole new translation?

**Comment by Quenty31** [comment]
@phy25 Mastodon, Funkwhale, YunoHost, JitsiMeet, Firefox, PluXml, Wordpress, Ubuntu have it :) And Wikipèdia of course

**Comment by phy25** [comment]
@Quenty31 Thanks, I googled that... Just don't know much about things in Europe... Though this is a minimal translation, it's a good starting point.

**Comment by Quenty31** [comment]
@phy25 just found this lovely article if you want some reading :) 
http://www.bbc.com/travel/story/20180911-occitan-the-language-the-french-forbade

**Pull request merged**
