### PR TITLE
remove deleted files on update of extension

### LINKED ISSUE #1192: Standard mechanism to delete files from plugin directory
For the ODT plugin I like to move from `action.php` to two components in the `action/` folder.
This is not possible because the `action.php` cannot be removed from the folder.

Is this worth a mechanism that let the plugin author remove blacklisted files?

`/lib/plugins/<plugin>/deleted.files`
which list files that can be removed e.g.
```
# This is a list of files that were present in previous plugin releases
# but were removed later. An up to date plugin should not have any of
# the files installed
action.php
folder/file.txt
```

### PR DESCRIPTION
**Pull request by Klap-in**
Resolves #1192 by supporting:

`/lib/plugins/<plugin>/deleted.files`
which list files that can be removed e.g.
```
# This is a list of files that were present in previous plugin releases
# but were removed later. An up to date plugin should not have any of
# the files installed
action.php
folder/file.txt
```

### CODE REVIEW

**Comment by Klap-in** [comment]
**Question:**

If I install a branch of the ODT plugin, then I got all the included files as duplicated .gz file.
https://github.com/LarsGit223/dokuwiki-plugin-odt/archive/deletedfiles.zip

Can someone reproduce that?

**Comment by splitbrain** [comment]
:+1: looks good to me

**Comment by Klap-in** [comment]
Makes this still chance to be included in Detritus? :-)

**Comment by splitbrain** [comment]
sure :-)

**Comment by Klap-in** [comment]
nice!

**Pull request merged**
