### PR TITLE
Set User-Agent header to 'DokuWiki HTTP Client (Extension Manager)'

### PR DESCRIPTION
**Pull request by LarsGit223**
This fixes download/installation problems for plugins which are hosted on SourceForge.

### CODE REVIEW

**Comment by splitbrain** [comment]
I think instead of adding another parameter to the io_download method, I would prefer to let the Extension manager instantiate it's own DokuHTTPClient, doing the download without io_download's help

**Comment by LarsGit223** [comment]
Ok, will have a look into that.

**Comment by LarsGit223** [comment]
Done.

**Comment by LarsGit223** [comment]
It would be cool if this could be merged so that we can re-run the check for the extension cleanup and see how many plugins are fixed by this.

**Pull request merged**
