### PR TITLE
Fix the flow of the navigation buttons in user manager

### PR DESCRIPTION
**Pull request by wilminator**

### CODE REVIEW

**Comment by wilminator** [comment]
This change is to fix aesthetics in the user manager GUI.  This changes allows for the pagination buttons to actually flow to the right of the table.

**Comment by splitbrain** [comment]
pre/post screenshot?

**Comment by wilminator** [comment]
Old:
image
New:
image

**Comment by selfthinker** [comment]
I think the only issue is that the `medialeft` span doesn't close. That seems to have been introduced in ae614416a5d7f5cab6c5b82a0c45f587d7fa9c01.

**Comment by wilminator** [comment]
I didn't investigate if the medialeft span is styled to occupy 100% of the table width.  I felt that adjusting that span to contain the full width of the screen so the mediaright could float to the right side of the table was the wrong direction to go, so I split them out.  My edit makes them two peer elements contained by a tr element instead of nested spans.

**Comment by selfthinker** [comment]
But it was intended differently (which is how it was before Detritus):

usermanager-buttons

Some buttons were on the left, some were in the middle and some were on the right. In your solution we'll only have left and right and no distinction between the main action (left) and the additional actions (middle).

**Comment by selfthinker** [comment]
> My edit makes them two peer elements contained by a tr element instead of nested spans.

They were peer elements before and no nested spans.

**Comment by wilminator** [comment]
Ah- that makes sense. Please correct me if I'm wrong, but then all I'm doing is proposing a fix that doesn't quite put the gui back the way it was.

**Comment by wilminator** [comment]
What's the best way to proceed from here?

**Comment by selfthinker** [comment]
I would just fix it by closing the span [here](https://github.com/splitbrain/dokuwiki/blob/master/lib/plugins/usermanager/admin.php#L245) like it was before.
You can then either force push a different commit to the same branch or create a new branch and a new PR.

**Comment by wilminator** [comment]
Sounds good. I will get the correct fix pushed back up shortly

**Comment by wilminator** [comment]
I think I have made the recommended change...  Please verify.

**Comment by selfthinker** [comment]
Yes, that's what I meant.
It would be nice to have this in just one commit but leaving it like it is is probably fine. :+1:

**Pull request merged**
