### PR TITLE
Initial batch of Minnan localization

### PR DESCRIPTION
**Pull request by GJRobert**
For background, see #3321.

### CODE REVIEW

**Comment by Klap-in** [comment]
Ah, moment, this just English...

**Comment by GJRobert** [comment]
I have translated the first batch of 30~40 strings into Minnan in [inc/lang/nan/lang.php](https://github.com/splitbrain/dokuwiki/pull/3323/files#diff-47668707edaaddb32214951dc0b2c82c4e795979e828c972bb98d2443aaec02d). Since I'm new to DW i18n, please feel free to instruct if any practice I can improve. Thanks!

**Comment by Klap-in** [comment]
Normally we prefer to submit only the actual translated strings, because now the translation tool sorts these English strings also a ‘translated’ strings backward. You have now to browser further to see them back between the available strings.

**Comment by GJRobert** [comment]
> Normally we prefer to submit only the actual translated strings, because now the translation tool sorts these English strings also a ‘translated’ strings backward. You have now to browser further to see them back between the available strings.

Wow, I'm sorry for that. Will it improve if I make a new commit with only translated strings?

**Comment by Klap-in** [comment]
Yeah, a pull request with only translated strings is helpful for you and other `nan` translators. Thanks!

**Comment by Klap-in** [comment]
Untranslated txt-files can also be deleted as well, DokuWiki itself use automatically the English version, if not yet translated. If you use the translation tool, these texts will pop up as well, without need for temporary English copies.

**Comment by GJRobert** [comment]
> Untranslated txt-files can also be deleted as well, DokuWiki itself use automatically the English version, if not yet translated. If you use the translation tool, these texts will pop up as well, without need for temporary English copies.

Thanks for confirming! I will surely remove those other files. (I have also tested on my DW-nan installation with the same safely fallen-back result as you mentioned).

**Pull request merged**
