### PR TITLE
Translation update (ar)

### PR DESCRIPTION
**Pull request by dokuwiki-translate**
This pull request contains some translation updates.

### CODE REVIEW

**Comment by Klap-in** [comment]
This was a test submit.

Submitting Arabic language seems to work again...

**Comment by Klap-in** [comment]
Related to: https://github.com/splitbrain/dokuwiki/issues/1621

**Comment by ahmgeek** [comment]
I am curuios about [that line] that line actually: (https://github.com/splitbrain/dokuwiki/pull/1651/commits/1f4354f737acce6be415a37ab1d9fa912d2abbc2#diff-d408a45f8b6ee3b8d71685a7bf7b16beR79)

**Comment by Klap-in** [comment]
Could you explain what is curious?

The English text were my additions and the rest are whitespace fixes of the translation tool. So for me these changes looks ok...

**Comment by ahmgeek** [comment]
I can't relate to the code, to be exact `$lang['regfail'] ` but I wonder why there's a test English chars inside 
a translation to an Arabic.

I also don't know what's the progress or if the Arabic support has stopped, I could give a hand in translation if you wish folks..

**Comment by splitbrain** [comment]
@ahmgeek, as @Klap-in said, that string was for testing the translation interface only. It was not merged.

Your help with the translation would be more than welcome. Please go to http://translate.dokuwiki.org for submitting new translations.

**Comment by Klap-in** [comment]
Previous translations got stuck in the translation tool. So therefore this test with some random English chars. The system appears to work fine again. If you experience strange behavior please mentioned it directly, then I can still recover the submitted data :)

**Pull request closed without merging**
