### PR TITLE
Added spans and css-classes to the rss rendering

### PR DESCRIPTION
**Pull request by s-blu**
Added CSS Classes to provide better possibilities for CSS formatting

### CODE REVIEW

**Comment by selfthinker** [comment]
The items themselves don't need an extra class, they can be targeted with `ul.rss li`.
Adding the spans for the author and date is generally a good idea but I would not be so specific and just give them the classes of `author` and `date` respectively (and not rename the existing `detail`).

Can you please test your changes first before submitting a pull request? There is a simple parsing error which prevents pages from loading at all and is the reason why the tests are failing.

**Comment by splitbrain** [comment]
@s-blu can you fix this please?

**Comment by s-blu** [comment]
Oh sorry, i thought this request was already closed. I changed the request as suggested and found my naughty parsing error. Sorry about that! :(

**Comment by selfthinker** [comment]
Sorry for the late reply.
Why did you give the `li` the class of `rss_item`? As I explained before, you can already target the list items without any additional class.

And again you do not seem to have tested your changes. You deleted the spaces between title, author and date and now every item reads like "Title linkby someone(2015/11/05 21:00)".

**Comment by s-blu** [comment]
Sorry for the trouble I didn't invested enough time for this change. I'll reopen this once I reworked it.

**Pull request closed without merging**
