### PR TITLE
Switch to phpunit 8 (fixes #2693)

### LINKED ISSUE #2693: Broken Tests on PHPUnit 8
PHPUnit recently releases version 8 (which is now the default on Travis CI PHP 7.2 environment). It [introduces "Return Type of Template Methods"](https://phpunit.de/announcements/phpunit-8.html), which is [failing DokuWiki's tests on PHP 7.2](https://travis-ci.org/splitbrain/dokuwiki/jobs/490896345#L476).

Looks like it will be very difficult to make tests work on both versions, since return type hinting is not compatible with PHP 5 (and we still need to support that). If we cannot find a way to support both, we have to make our Travis CI environment stick to PHPUnit 7, or tests on PHP 7.2 will always fail.

### PR DESCRIPTION
**Pull request by splitbrain**
This switches to PHPUnit 8 to be able to test on PHP8. This means we have to finally adopt the return hints of inherited methods  (and thus break the tests of a lot of plugins). 

This PR does not enable testing on PHP8 on github, yet. The idea is to merge this first, then use it to tackle all the PHP8 problems surfaced by the tests (about 25 currently).

### CODE REVIEW

**Comment by splitbrain** [comment]
@dregad maybe you want to help further with the PHP compatibility by running the tests?

**Comment by splitbrain** [comment]
The failing Windows tests are super weird and I am not sure they are related to anything I did here. I will retry them in a while in hopes they are a fluke with github's windows runner.

**Comment by dregad** [comment]
> @dregad maybe you want to help further with the PHP compatibility by running the tests?

Sure. Here's the results of a run on my dev box (Ubuntu 20.04, PHP 8.0.1):
**Tests: 1666, Assertions: 27000, Errors: 30, Failures: 2, Skipped: 102.**

It's a bit late for me to start looking into it, so I'll just post the raw output for now.

```
PHPUnit 8.5.14 by Sebastian Bergmann and contributors.

......E.E....................................................   61 / 1666 (  3%)
.............................................................  122 / 1666 (  7%)
.............................................................  183 / 1666 ( 10%)
............................S................................  244 / 1666 ( 14%)
.................................................E...........  305 / 1666 ( 18%)
............................................................E  366 / 1666 ( 21%)
EE...............................................EE.EE.......  427 / 1666 ( 25%)
.........................................E.......E...........  488 / 1666 ( 29%)
...............SSSE..............SSSE.........EE.............  549 / 1666 ( 32%)
..........................EE.................................  610 / 1666 ( 36%)
.............................................................  671 / 1666 ( 40%)
............S................................................  732 / 1666 ( 43%)
.............................................................  793 / 1666 ( 47%)
.............................................................  854 / 1666 ( 51%)
.............................................................  915 / 1666 ( 54%)
.............................................................  976 / 1666 ( 58%)
....................................................E.E...... 1037 / 1666 ( 62%)
............................................................. 1098 / 1666 ( 65%)
..................E................EE................E....E.. 1159 / 1666 ( 69%)
...........F...............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 1220 / 1666 ( 73%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.......... 1281 / 1666 ( 76%)
............................................................. 1342 / 1666 ( 80%)
............................................................. 1403 / 1666 ( 84%)
............................................................. 1464 / 1666 ( 87%)
..................E....EE...........EF................SSSSSSS 1525 / 1666 ( 91%)
SS........................................................... 1586 / 1666 ( 95%)
............................................................. 1647 / 1666 ( 98%)
.................E.                                           1666 / 1666 (100%)

Time: 1.77 minutes, Memory: 62.50 MB
```

## There were 30 errors:
```
1) general_html_test::test_Validity with data set #5 ('/doku.php', 'GET', array('wiki:syntax'))
Required parameter $working follows optional parameter $type

/home/dregad/dev/dokuwiki/dokuwiki/vendor/simplepie/simplepie/library/SimplePie/Locator.php:97
/home/dregad/dev/dokuwiki/dokuwiki/vendor/composer/ClassLoader.php:444
/home/dregad/dev/dokuwiki/dokuwiki/vendor/composer/ClassLoader.php:444
/home/dregad/dev/dokuwiki/dokuwiki/vendor/composer/ClassLoader.php:322
/home/dregad/dev/dokuwiki/dokuwiki/vendor/simplepie/simplepie/library/SimplePie/Registry.php:176
/home/dregad/dev/dokuwiki/dokuwiki/vendor/simplepie/simplepie/library/SimplePie.php:1644
/home/dregad/dev/dokuwiki/dokuwiki/vendor/simplepie/simplepie/library/SimplePie.php:1381
/home/dregad/dev/dokuwiki/dokuwiki/inc/parser/xhtml.php:1309
/home/dregad/dev/dokuwiki/dokuwiki/inc/parserutils.php:673
/home/dregad/dev/dokuwiki/dokuwiki/inc/parserutils.php:142
/home/dregad/dev/dokuwiki/dokuwiki/inc/parserutils.php:89
/home/dregad/dev/dokuwiki/dokuwiki/inc/Ui/PageView.php:68
/home/dregad/dev/dokuwiki/dokuwiki/inc/Action/Show.php:37
/home/dregad/dev/dokuwiki/dokuwiki/inc/template.php:99
/home/dregad/dev/dokuwiki/dokuwiki/inc/Extension/Event.php:133
/home/dregad/dev/dokuwiki/dokuwiki/inc/Extension/Event.php:199
/home/dregad/dev/dokuwiki/dokuwiki/inc/template.php:84
/home/dregad/dev/dokuwiki/dokuwiki/lib/tpl/dokuwiki/main.php:58
/home/dregad/dev/dokuwiki/dokuwiki/inc/actions.php:27
/home/dregad/dev/dokuwiki/dokuwiki/doku.php:122
/home/dregad/dev/dokuwiki/dokuwiki/_test/core/TestRequest.php:159
/home/dregad/dev/dokuwiki/dokuwiki/_test/core/TestRequest.php:242
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/general/general_html.test.php:98

2) general_html_test::test_Validity with data set #7 ('/lib/exe/detail.php', 'GET', array('wiki:syntax', 'wiki:dokuwiki-128.png'))
Undefined array key 3

/home/dregad/dev/dokuwiki/dokuwiki/inc/template.php:1071
/home/dregad/dev/dokuwiki/dokuwiki/inc/template.php:1029
/home/dregad/dev/dokuwiki/dokuwiki/lib/tpl/dokuwiki/detail.php:58
/home/dregad/dev/dokuwiki/dokuwiki/lib/exe/detail.php:45
/home/dregad/dev/dokuwiki/dokuwiki/_test/core/TestRequest.php:159
/home/dregad/dev/dokuwiki/dokuwiki/_test/core/TestRequest.php:242
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/general/general_html.test.php:98

3) changelog_getlastrevisionat_test::test_deletedimage
Undefined array key "REMOTE_USER"

/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/changelog_getlastrevisionat.test.php:143

4) common_clientIP_test::test_garbageonly_all
Undefined array key 0

/home/dregad/dev/dokuwiki/dokuwiki/inc/common.php:825
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/common_clientip.test.php:169

5) common_clientIP_test::test_garbageonly_single
Undefined array key 0

/home/dregad/dev/dokuwiki/dokuwiki/inc/common.php:825
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/common_clientip.test.php:177

6) common_clientIP_test::test_malicious
Undefined array key 0

/home/dregad/dev/dokuwiki/dokuwiki/inc/common.php:825
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/common_clientip.test.php:185

7) common_saveWikiText_test::test_savesequence
Undefined array key "date"

/home/dregad/dev/dokuwiki/dokuwiki/inc/parserutils.php:414
/home/dregad/dev/dokuwiki/dokuwiki/inc/common.php:1400
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/common_saveWikiText.test.php:101

8) common_saveWikiText_test::test_savesequencedeleteexternalrevision
Undefined array key "date"

/home/dregad/dev/dokuwiki/dokuwiki/inc/parserutils.php:414
/home/dregad/dev/dokuwiki/dokuwiki/inc/common.php:1400
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/common_saveWikiText.test.php:196

9) common_saveWikiText_test::test_savesequenceexternaldeleteedit
Undefined array key "creator"

/home/dregad/dev/dokuwiki/dokuwiki/inc/changelog.php:115
/home/dregad/dev/dokuwiki/dokuwiki/inc/common.php:1422
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/common_saveWikiText.test.php:302

10) common_saveWikiText_test::test_savesequencerevert
Undefined array key "creator"

/home/dregad/dev/dokuwiki/dokuwiki/inc/changelog.php:115
/home/dregad/dev/dokuwiki/dokuwiki/inc/common.php:1422
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/common_saveWikiText.test.php:407

11) fulltext_backlinks_test::test_links_in_deleted_pages
Undefined array key "date"

/home/dregad/dev/dokuwiki/dokuwiki/inc/parserutils.php:414
/home/dregad/dev/dokuwiki/dokuwiki/inc/common.php:1400
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/fulltext_backlinks.test.php:72

12) fultext_mediause_test::test_media_in_deleted_pages
Undefined array key "date"

/home/dregad/dev/dokuwiki/dokuwiki/inc/parserutils.php:414
/home/dregad/dev/dokuwiki/dokuwiki/inc/common.php:1400
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/fulltext_mediause.test.php:79

13) httpclient_http_test::test_cookies
Undefined array key "port"

/home/dregad/dev/dokuwiki/dokuwiki/inc/HTTP/HTTPClient.php:376
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/httpclient_mock.php:45
/home/dregad/dev/dokuwiki/dokuwiki/inc/HTTP/HTTPClient.php:100
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/httpclient_http.test.php:139

14) httpclient_https_test::test_cookies
Undefined array key "port"

/home/dregad/dev/dokuwiki/dokuwiki/inc/HTTP/HTTPClient.php:376
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/httpclient_mock.php:45
/home/dregad/dev/dokuwiki/dokuwiki/inc/HTTP/HTTPClient.php:100
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/httpclient_http.test.php:139

15) httpclient_https_proxy_test::test_connectfail
Undefined array key "path"

/home/dregad/dev/dokuwiki/dokuwiki/inc/HTTP/HTTPClient.php:181
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/httpclient_mock.php:45
/home/dregad/dev/dokuwiki/dokuwiki/inc/HTTP/HTTPClient.php:100
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/httpclient_https_proxy.test.php:26

16) httpclient_https_proxy_test::test_simpleget
Undefined array key "port"

/home/dregad/dev/dokuwiki/dokuwiki/inc/HTTP/HTTPClient.php:514
/home/dregad/dev/dokuwiki/dokuwiki/inc/HTTP/HTTPClient.php:268
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/httpclient_mock.php:45
/home/dregad/dev/dokuwiki/dokuwiki/inc/HTTP/HTTPClient.php:100
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/httpclient_http_proxy.test.php:17

17) input_test::test_remove
Undefined array key "string"

/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/input.test.php:230

18) input_test::test_set
Undefined array key "test"

/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/input.test.php:248

19) TestOfDoku_Parser_Media::testVideoOGVExternal
Undefined array key "title"

/home/dregad/dev/dokuwiki/dokuwiki/inc/parser/xhtml.php:1890
/home/dregad/dev/dokuwiki/dokuwiki/inc/parser/xhtml.php:1694
/home/dregad/dev/dokuwiki/dokuwiki/inc/parser/xhtml.php:1829
/home/dregad/dev/dokuwiki/dokuwiki/inc/parser/xhtml.php:1260
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/parser/parser_media.test.php:27

20) TestOfDoku_Parser_Media::testVideoOGVInternal
Undefined array key "title"

/home/dregad/dev/dokuwiki/dokuwiki/inc/parser/xhtml.php:1890
/home/dregad/dev/dokuwiki/dokuwiki/inc/parser/xhtml.php:1694
/home/dregad/dev/dokuwiki/dokuwiki/inc/parser/xhtml.php:1829
/home/dregad/dev/dokuwiki/dokuwiki/inc/parser/xhtml.php:1260
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/parser/parser_media.test.php:104

21) Test_resolveInterwiki::testNonexisting
Uninitialized string offset 0

/home/dregad/dev/dokuwiki/dokuwiki/inc/parser/renderer.php:892
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/parser/renderer_resolveinterwiki.test.php:50

22) parserutils_set_metadata_test::test_array_replace
Undefined array key "id"

/home/dregad/dev/dokuwiki/dokuwiki/inc/parserutils.php:466
/home/dregad/dev/dokuwiki/dokuwiki/inc/parserutils.php:398
/home/dregad/dev/dokuwiki/dokuwiki/inc/changelog.php:122
/home/dregad/dev/dokuwiki/dokuwiki/inc/common.php:1422
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/parserutils_set_metadata.test.php:52

23) parserutils_set_metadata_during_rendering_test::test_p_set_metadata_during_rendering
Undefined array key 2

/home/dregad/dev/dokuwiki/dokuwiki/inc/parser/handler.php:136
/home/dregad/dev/dokuwiki/dokuwiki/inc/Parsing/Parser.php:123
/home/dregad/dev/dokuwiki/dokuwiki/inc/parserutils.php:216
/home/dregad/dev/dokuwiki/dokuwiki/inc/parserutils.php:181
/home/dregad/dev/dokuwiki/dokuwiki/inc/parserutils.php:501
/home/dregad/dev/dokuwiki/dokuwiki/inc/parserutils.php:282
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/parserutils_set_metadata_during_rendering.test.php:30

24) remote_test::test_notExistingCall
Undefined array key 1

/home/dregad/dev/dokuwiki/dokuwiki/inc/Remote/Api.php:95
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/remote.test.php:371

25) remote_test::test_pluginCallCustomPath
Undefined array key "methodString"

/home/dregad/dev/dokuwiki/dokuwiki/inc/Remote/Api.php:167
/home/dregad/dev/dokuwiki/dokuwiki/inc/Remote/Api.php:132
/home/dregad/dev/dokuwiki/dokuwiki/inc/Remote/Api.php:102
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/remote.test.php:420

26) InttestsBasicTest::testScripts
Constant DOKU_MEDIADETAIL already defined

/home/dregad/dev/dokuwiki/dokuwiki/lib/exe/detail.php:6
/home/dregad/dev/dokuwiki/dokuwiki/_test/core/TestRequest.php:159
/home/dregad/dev/dokuwiki/dokuwiki/_test/core/TestRequest.php:242
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/test/basic.test.php:137

27) EditAndSaveTest::testEditSaveRedirect_Headline2_A
Undefined array key "date"

/home/dregad/dev/dokuwiki/dokuwiki/inc/Action/Save.php:47
/home/dregad/dev/dokuwiki/dokuwiki/inc/ActionRouter.php:83
/home/dregad/dev/dokuwiki/dokuwiki/inc/ActionRouter.php:48
/home/dregad/dev/dokuwiki/dokuwiki/inc/ActionRouter.php:60
/home/dregad/dev/dokuwiki/dokuwiki/inc/actions.php:16
/home/dregad/dev/dokuwiki/dokuwiki/doku.php:122
/home/dregad/dev/dokuwiki/dokuwiki/_test/core/TestRequest.php:159
/home/dregad/dev/dokuwiki/dokuwiki/_test/core/TestRequest.php:229
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/test/edit_and_save.test.php:80

28) EditAndSaveTest::testEditSaveRedirect_Headline2_B
Undefined array key "date"

/home/dregad/dev/dokuwiki/dokuwiki/inc/Action/Save.php:47
/home/dregad/dev/dokuwiki/dokuwiki/inc/ActionRouter.php:83
/home/dregad/dev/dokuwiki/dokuwiki/inc/ActionRouter.php:48
/home/dregad/dev/dokuwiki/dokuwiki/inc/ActionRouter.php:60
/home/dregad/dev/dokuwiki/dokuwiki/inc/actions.php:16
/home/dregad/dev/dokuwiki/dokuwiki/doku.php:122
/home/dregad/dev/dokuwiki/dokuwiki/_test/core/TestRequest.php:159
/home/dregad/dev/dokuwiki/dokuwiki/_test/core/TestRequest.php:229
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/test/edit_and_save.test.php:163

29) tests\inc\Subscriptions\BulkSubscriptionsSenderTest::testBulkdigest
Undefined array key "mailfromnobody"

/home/dregad/dev/dokuwiki/dokuwiki/inc/Subscriptions/SubscriptionSender.php:74
/home/dregad/dev/dokuwiki/dokuwiki/inc/Subscriptions/PageSubscriptionSender.php:78
/home/dregad/dev/dokuwiki/dokuwiki/inc/Subscriptions/BulkSubscriptionSender.php:207
/home/dregad/dev/dokuwiki/dokuwiki/inc/Subscriptions/BulkSubscriptionSender.php:106
/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/Subscriptions/BulkSubscriptionsSenderTest.php:47

30) dokuwiki\plugin\config\test\WriterTest::testSave
Undefined array key "REMOTE_USER"

/home/dregad/dev/dokuwiki/dokuwiki/lib/plugins/config/core/Writer.php:113
/home/dregad/dev/dokuwiki/dokuwiki/lib/plugins/config/core/Writer.php:46
/home/dregad/dev/dokuwiki/dokuwiki/lib/plugins/config/_test/WriterTest.php:32
```

## There were 2 failures:
```
1) remoteapicore_test::test_getBacklinks
Failed asserting that false is true.

/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/remoteapicore.test.php:308

2) tests\inc\Subscriptions\BulkSubscriptionsSenderTest::testBulklist
Failed asserting that 0 matches expected 1.

/home/dregad/dev/dokuwiki/dokuwiki/_test/tests/inc/Subscriptions/BulkSubscriptionsSenderTest.php:89

ERRORS!
Tests: 1666, Assertions: 27000, Errors: 30, Failures: 2, Skipped: 102.
```

## Plugin failure

It's worth mentioning that the unit tests would not even run until I removed the _move_ plugin.

```
PHP Fatal error:  Declaration of plugin_move_affectedPagesNS_test::setUp() must be compatible with DokuWikiTest::setUp(): void in /home/dregad/dev/dokuwiki/dokuwiki/lib/plugins/move/_test/affectedPagesNs.test.php on line 14

Fatal error: Declaration of plugin_move_affectedPagesNS_test::setUp() must be compatible with DokuWikiTest::setUp(): void in /home/dregad/dev/dokuwiki/dokuwiki/lib/plugins/move/_test/affectedPagesNs.test.php on line 14
```

**Comment by dregad** [comment]
About this one
> 23) parserutils_set_metadata_during_rendering_test::test_p_set_metadata_during_rendering
Undefined array key 2

This error occurs because the test is replacing the plugin controller with a dummy one, and [injects a call which does not have the same structure as other calls](https://github.com/splitbrain/dokuwiki/blob/phpunit8/_test/tests/inc/parserutils_set_metadata_during_rendering.test.php#L64).

I'm not sure if the proper fix for this, is to adjust the test case (i.e. add 3rd entry to the array in helper_inject_test_instruction()) , or if it is an otherwise normal scenario to have parser calls without key # 2 defined, in which case the fix should be applied in Doku_Handler::finalize().

Please advise.

**Comment by dregad** [comment]
This one I'm also not sure how to fix
> 25) remote_test::test_pluginCallCustomPath
Undefined array key "methodString"

Error occurs in Api::callPlugin(), on statement `$this->checkAccess($methods[$method]);`

In the *$methods* array, keys are defined as `plugin.testplugin.xxxx`, while *$method* is `methodString` so the key does not exist. In PHP < 8, checkAccess() would then be called with *null*, but I'm thinking that the actual intention is to get the method's meta from the  `plugin.testplugin.methodString` and I don't know what is the proper way of doing this.

**Comment by dregad** [comment]
PR #3406 fixes most of the error cases; see my above comments.

> 1) general_html_test::test_Validity with data set #5 ('/doku.php', 'GET', array('wiki:syntax'))
Required parameter $working follows optional parameter $type

Can be fixed by updating simplepie (1.5.5 => 1.5.6)
```
composer update simplepie/simplepie
```
As I'm not familiar with the process to follow when updating libraries, I'll let you handle that

**Comment by splitbrain** [comment]
It seems the Windows tests have not fixed themselves and are somehow caused by a change in this PR. I still do not understand what's going on but it needs to be addressed before this can be merged.

**Comment by dregad** [comment]
I don't use Windows and I'm not familiar with Github actions, but considering that the tests pass on Linux and looking at the warnings in the log which complain about file permissions, could it be that the failure caused by the Windows runners' setup in a PHPUnit 8.x context ?

>Warning: PHP Warning:  copy(C:/Users/RUNNER~1/AppData/Local/Temp/dwtests-1612774630.1288/data/media/wiki/dokuwiki-128.png): failed to open stream: Permission denied in D:\a\dokuwiki\dokuwiki\_test\core\TestUtils.php on line 26
>
>Warning: ..PHP Warning:  unlink(C:/Users/RUNNER~1/AppData/Local/Temp/dwtests-1612774630.1288/data//media/wiki/dokuwiki-128.png): Permission denied in D:\a\dokuwiki\dokuwiki\_test\core\TestUtils.php on line 52
>
>1\) remoteapicore_test::test_getVersion
unlink(C:/Users/RUNNER~1/AppData/Local/Temp/dwtests-1612774630.1288/data//media/wiki/dokuwiki-128.png): Permission denied
```

**Comment by dregad** [comment]
> C:/Users/RUNNER~1/AppData/Local/Temp/dwtests-1612774630.1288/data//media/wiki/dokuwiki-128.png

Wondering if the double slash `data//media` could be causing the problem ?

**Comment by dregad** [comment]
> Wondering if the double slash `data//media` could be causing the problem ?

OK so that was a red herring...

What is really strange is that if the whole test suite is executed, it fails on *remoteapicore_test*, but if only that single unit is executed, the test passes :confused:

After some trial and error debugging, I still have not found the root cause, but made some progress; here are my findings:

1. Problem always occurs when trying to access media file `dokuwiki-128.png`; this happens in DokuWikiTest::setupDataDir(), for an unknown reason the file cannot be deleted. I checked permissions by adding a debugging fileperms() call in TestUtils::rdelete(), but it results in 
  ```
  PHP Warning:  fileperms(): stat failed for C:/Users/RUNNER~1/AppData/Local/Temp/dwtests-1612857770.3724/data/media/wiki/dokuwiki-128.png in D:\a\dokuwiki\dokuwiki\_test\core\TestUtils.php on line 53
  ```
  No idea why _stat_ fails and also don't know how to find out the reason.

2. It begins after executing the _general_html_test_ or the _InttestsGlobalsTest_ suites. Excluding these from the run (i.e. adding `--filter '^(?!general_html_test|InttestsBasicTest)'` to the _Run PHPUnit_ step in testWindows.yml results in a successful execution (see dregad@937a4bf4861a464aecbd6fe9f2c4c1052c62fde0).

3. Narrowing it down, it seems that the offender is a call to `/lib/exe/detail.php` - removing this, again yields a successful execution (see dregad@6924a7d2dea129b34aee305473cadb5ca7dcd3c3) so we have a workaround.

So I still have no real idea what is happening and why, but at least we know more precisely what is triggering the problem. Maybe someone with deeper knowledge of DokuWiki internals can research further from here.

**Comment by splitbrain** [comment]
Thank you @dregad for your research. It brought me on the right track. After some poking on a VM I found the culprit. See 01c53a65419273208ff4c5e111338e35f88c1394 for the fix.

**Comment by splitbrain** [comment]
Only two issues remaining

> parserutils_set_metadata_during_rendering_test::test_p_set_metadata_during_rendering
> Undefined array key 2

Here I'd say fixing the test to match "normal" instructions is the way to go

> remoteapicore_test::test_getBacklinks
> Failed asserting that false is true.

Not sure why this one is failing, yet.

**Comment by micgro42** [comment]
> Only two issues remaining
> 
> > parserutils_set_metadata_during_rendering_test::test_p_set_metadata_during_rendering
> > Undefined array key 2
> 
> Here I'd say fixing the test to match "normal" instructions is the way to go
> 
> > remoteapicore_test::test_getBacklinks
> > Failed asserting that false is true.
> 
> Not sure why this one is failing, yet.

I'm looking into this right now. Seems those two failures are related. `remoteapicore_test::test_getBacklinks` only fails if `parserutils_set_metadata_during_rendering_test::test_p_set_metadata_during_rendering` is run

**Pull request merged**
