### PR TITLE
Fix #3619 and correctly handle exceptions in XMLRPC

### LINKED ISSUE #3619: xmlrpc: Error: Class "IXR_Error" not found
Got error in logs:
```
2022-02-03 12:26:53	/usr/local/www/wiki/lib/exe/xmlrpc.php(13)	Error: Class "IXR_Error" not found
  #0 {main}
```
if ```remote``` is disabled.

https://github.com/splitbrain/dokuwiki/blob/master/lib/exe/xmlrpc.php#L13
probably some include was missed and this line generates error.

### PR DESCRIPTION
**Pull request by splitbrain**
This ensures that any exception happening during XMLRPC processing is
signalled correctly to the client as XML encoded error message.

### CODE REVIEW

**Comment by Klap-in** [comment]
@satwareAG-ironMike and @rozhuk-im could you review this?

**Comment by rozhuk-im** [comment]
```
2022-02-04 22:26:37	/usr/local/www/wiki/inc/Remote/XmlRpcServer.php(24)	IXR\Exception\ServerException: XML-RPC server not enabled.
  #0 /usr/local/www/wiki/lib/exe/xmlrpc.php(13): dokuwiki\Remote\XmlRpcServer->__construct()
  #1 {main}
```
in log, but dokuwiki android client got
```
XmlRpc call wiki.getPageHTML error: org.apache.xmlrpc.client.XmlRpcClientException: Failed to parse server's response: Expected methodResponse element, got html
```

I expect that client will receive: "XML-RPC server not enabled."  error message and do not get error messages in log.

**Comment by splitbrain** [comment]
@rozhuk-im did you actually use the correct branch?

**Comment by rozhuk-im** [comment]
4ef5d38db53e045a81f129b29a8b886cecc38497 + 4b867325b0bce2a430cace11805d1b09c43f1ee1

**Comment by splitbrain** [comment]
Ah you're right. I aborted too early... should work now.

**Comment by rozhuk-im** [comment]
Now client receive: ```XmlRpc call dokuwiki.getTitle error: org.apache.xmlrpc.XmlRpcException: XML-RPC server not enabled.```
and I see no errors in log.
Looks like fixed, thanks!

**Review by rozhuk-im — APPROVED** [review]

**Pull request merged**
