### PR TITLE
Update `deleted.files` with files removed in #3344

### PR DESCRIPTION
**Pull request by mprins**
#3344 replaced `.gif` smileys with `.svg`

### CODE REVIEW

**Comment by Klap-in** [comment]
This is logic consequence of removing it from git. 

But a more principal question, should we not keep the images for one release, to give plugin authors time to update?
And delete it the next release?

**Comment by Klap-in** [comment]
Should we not restore the gifs, and deprecate them this release. So that we can remove them next release according to the default depreciation scheme?

**Comment by splitbrain** [comment]
@Klap-in do we know of anyone making use of them in a plugin? If yes, I'm fin with restoring them for now.

**Comment by Klap-in** [comment]
Here, issues opened at plugins https://github.com/splitbrain/dokuwiki/pull/3344#issuecomment-1007713674 .
prosemirror was using the gifs explicitly. 
Most others are about svg vs gif.

**Comment by mprins** [comment]
can this be merged now? since we now have a release and a patch release out without the `.gif` smileys

**Pull request merged**
