### PR TITLE
New LESS parser

### PR DESCRIPTION
**Pull request by splitbrain**
this requires the merge of the composer branch, so please look at #1152 first.

This PR adds the oyejorge LESS library and removes the now unmaintained lessphp library. From what I understand, Caching is disabled by default in the library so only our own caching is used.

@Chris--S @michitux @gamma @bug please have a look

### CODE REVIEW

**Comment by Chris--S** [comment]
:+1:

**Comment by bug** [comment]
Clean for me.

**Comment by bug** [comment]
If we merge that, #983 can be cleared

**Comment by splitbrain** [comment]
It seems combining Apache licensed code with GPL2 is problematic. A dual license has been requested upstream but is waiting for a decision further upstream. It is unlikely that this will ever be resolved.

https://github.com/oyejorge/less.php/issues/148
https://github.com/less/less.js/issues/1029

**Comment by gamma** [comment]
Looks good to me. I just hope they will solve the licensing issues.

**Comment by splitbrain** [comment]
There's a fork of leafo/lessphp that seems to be well maintained: https://github.com/MarcusSchwarz/lesserphp it's MIT licensed. We should switch to it.

**Comment by splitbrain** [comment]
closing this in favor of #1969

**Pull request closed without merging**
