### PR TITLE
Linkwiz update (#3498)

### PR DESCRIPTION
**Pull request by alexdraconian**
This is pull request about issue #3498.

### CODE REVIEW

**Comment by sokolgeo** [comment]
The solution in the above commit #4668fa1 looks strange:
`// If search result is empty but 'useheading' option is 'always' or 'content',`
`// search page titles with original query.`

I mean if 'useheading' option is 'always' or 'content' we must **ALWAYS** search **first** pagetitles and either not  search by pagenames at all or amend the pagenames search results with the results from **mandatory** pagetitles search, no?

**Comment by alexdraconian** [comment]
I was actually afraid to make big behavior change, since this was my early contribute. That's why I made this function as 'sub function' - Whan search fails, it will look for pagetitles.

So your suggestion is that ONLY search with pagetitles when 'useheading' is 'always' or 'content', right? I agree with this, and will make changes if this is right.

**Comment by alexdraconian** [comment]
Okay, I've made changes to linkwiz always seaches with pagetitles, if 'useheading' option is 'always' or 'content'.

I decided to keep original search function with pagenames - Since there can be some pagetitles that contains special characters can't be entered with keyboard easily. (I meant ALWAYS instead of ONLY in above comment...)

**Comment by sokolgeo** [comment]
Thank you @alexdraconian 
How to test the above patch in my docuwiki instance, please?
Just go and patch the `inc/Ajax.php` manually as per the above three commits?

**Comment by alexdraconian** [comment]
@sokolgeo Right. If you encounter any bugs, please let me know.

**Comment by sokolgeo** [comment]
@alexdraconian 

Does not work.

- I placed the patched file into my Hogfather installation: https://raw.githubusercontent.com/splitbrain/dokuwiki/2aa917afb4705e3fab36c6d320984590d987c883/inc/Ajax.php
- I set "always" as headings option and saved configuration.
- I rebuilt search index with deletion of the old index, just in case.
- I restarted the PC, to reset any browser caching there might be.

Now In the link wizard I can see the first headings of my wiki pages listed, as it was originally, but entering these heading into search box in the link wizard results in "Nothing was found.".

Anything else I can try to make this work? Any explicit ways to reset the browser cache or anything else?

**Comment by sokolgeo** [comment]
> Can you test if this works? Change this line: `if ($conf['useheading'] === '1' || $conf['useheading'] === 'content') { ` (3 equal signs) to this: `if ($conf['useheading'] == '1' || $conf['useheading'] == 'content') { ` (2 equal signs)

This made the trick! All seems to be working as it should now! Thank you @alexdraconian 

> If you can, please open `conf/local.php` and check the value of `$conf['useheading']`. In my case, it was `'1'`. I wonder if your file says `1` (Without quotation mark)

This was already correctly stored without quotation marks, thank you for the tip.
 
> Note: You don't have to rebulid index and discard browser cache. In my case, just patch `ajax.php` and this worked. You can also press `Ctrl + F5` to refresh and delete cache in browser for that site.

Thank you.

Can you please update the commit with 2 equal signs? How could it land in the main tree for the next official release?

**Comment by alexdraconian** [comment]
I've updated and commit changed code.

Since I'm first-time contributor, maintainer must approve this pull request. I can't sure if this update become part of next release; I'm just contributor.

**Comment by sokolgeo** [comment]
Thank you for the patch @alexdraconian 
Shall we maybe ask @splitbrain to review it for inclusion into the main branch?

**Comment by gerardnico** [comment]
For your information, you can wrap you code in a action plugin that uses the [search_query_pagelookup](https://www.dokuwiki.org/devel:event:search_query_pagelookup) event if you don't want to wait for the approval.

**Pull request merged**
