### PR TITLE
Add height: auto to video element css

### LINKED ISSUE #1697: Relative Sizing for Media
I often insert screencasts (mp4 / webm video) into my wiki via the media manager. The default sizing for the videos is very small. I know I can change the absolute size with _?widthxheight_ on the file link, but with video this does not work too well. Specifying a large width causes the video to fit the page width, but the height is still very small. Specifying a large width and height causes the width to scale with the container but not the height. 

I've found that by specifying the size of a 720p video to 912x513 I get a good result on a desktop, but with a small viewport that width shrinks and you end up with a large 513px block with a small video inside of it.

### PR DESCRIPTION
**Pull request by KeenRivals**
Resolves #1697

### CODE REVIEW

**Comment by selfthinker** [comment]
I remember I initially added `height: auto;` to all media elements but that caused problems in some browsers. Unfortunately I don't remember what kind of problems they were and in which browsers.
I guess that means this should at least be properly browser-tested before it can be merged.

**Comment by KeenRivals** [comment]
Is there any way I can assist with browser testing?

**Comment by splitbrain** [comment]
@KeenRivals sure you can help with that. Simply test the feature in various browsers (mobile and desktop) and report back wich browsers you checked.

**Comment by KeenRivals** [comment]
I did some browser testing on the devices I have available and everything looks good. There's a table with screenshots below.

# Test Results

OS: Windows 10 (1607)

| Browser | Version | Result (Wide)| Result (Narrow) |
| ------- | ------- | ------------ | --------------- |
| Firefox Nightly | 53 | [Good](https://dl.dropboxusercontent.com/u/40722/dokuwiki-screens/desktop-windows/Firefox%20Nightly%2053.0a1%20Wide.png) | [Good](https://dl.dropboxusercontent.com/u/40722/dokuwiki-screens/desktop-windows/Firefox%20Nightly%2053.0a1%20Narrow.png) |
| Firefox | 50 | [Good](https://dl.dropboxusercontent.com/u/40722/dokuwiki-screens/desktop-windows/Firefox%2050%20Wide.png) | [Good](https://dl.dropboxusercontent.com/u/40722/dokuwiki-screens/desktop-windows/Firefox%2050%20Narrow.png) |
| Firefox ESR | 45 | [Good](https://dl.dropboxusercontent.com/u/40722/dokuwiki-screens/desktop-windows/Firefox%20ESR%2045.5%20Wide.png) | [Good](https://dl.dropboxusercontent.com/u/40722/dokuwiki-screens/desktop-windows/Firefox%20ESR%2045.5%20Narrow.png) |
| MS Edge | 38 | [Good](https://dl.dropboxusercontent.com/u/40722/dokuwiki-screens/desktop-windows/MS%20Edge%20Wide.png) | [Good](https://dl.dropboxusercontent.com/u/40722/dokuwiki-screens/desktop-windows/MS%20Edge%20Narrow.png) |
| Internet Explorer | 11 | [Good](https://dl.dropboxusercontent.com/u/40722/dokuwiki-screens/desktop-windows/Internet%20Explorer%2011%20Wide.png) | [Good](https://dl.dropboxusercontent.com/u/40722/dokuwiki-screens/desktop-windows/Internet%20Explorer%2011%20Narrow.png) |
| Internet Explorer (via modern.ie) | 10 | [Good](https://dl.dropboxusercontent.com/u/40722/dokuwiki-screens/modern.ie/win7_ie_10.0.png) | Did not test |
| Internet Explorer (via modern.ie) | 9 | [Good](https://dl.dropboxusercontent.com/u/40722/dokuwiki-screens/modern.ie/win7_ie_9.0.png) | Did not test |
| Chrome | 55 | [Good](https://dl.dropboxusercontent.com/u/40722/dokuwiki-screens/desktop-windows/Chrome%2055%20Wide.png) | [Good](https://dl.dropboxusercontent.com/u/40722/dokuwiki-screens/desktop-windows/Chrome%2055%20Narrow.png) |
| Safari (via modern.ie) | 9.1 | [Good](https://dl.dropboxusercontent.com/u/40722/dokuwiki-screens/modern.ie/macelc_safari_9.1.png) | Did not test |
| Firefox Mobile (Android) | 50 | [Good](https://dl.dropboxusercontent.com/u/40722/dokuwiki-screens/mobile-android/Firefox%2050%20Wide.png) | [Good](https://dl.dropboxusercontent.com/u/40722/dokuwiki-screens/mobile-android/Firefox%2050%20Narrow.png) |
| Chrome Mobile (Android) | 54 | [Good](https://dl.dropboxusercontent.com/u/40722/dokuwiki-screens/mobile-android/Chrome%2054%20Wide.png) | [Good](https://dl.dropboxusercontent.com/u/40722/dokuwiki-screens/mobile-android/Chrome%2054%20Narrow.png) |
| Safari on iPad Air (via modern.ie) | iOS 8.3 | [Good](https://dl.dropboxusercontent.com/u/40722/dokuwiki-screens/modern.ie/ios_iPad-Air_8.3_portrait.jpg) | Did not test |
| Safari on iPhone (via modern.ie) | iOS 8.3 | [Good](https://dl.dropboxusercontent.com/u/40722/dokuwiki-screens/modern.ie/ios_iPhone-6-Plus_8.3_portrait.jpg) | Did not test |

**Comment by selfthinker** [comment]
Thanks for testing and sharing the exhaustive test results.

I have just retested this as well (together with adding the auto height to all media elements). I couldn't find any problems when adding it to videos either, I think the problem I had a few years ago must have been for a specific old version of a browser.
When adding it to other media elements (audio, object, iframe, etc) it is still causing issues. I know, that is not what this PR is about, but I wanted to test it anyway as it could have made more sense to treat them together.

So, this looks good. :+1:

The only thing I might have done differently is to move the `height: auto` from the `img` and the `video` together as they are related and there for the same reason.

**Comment by selfthinker** [comment]
I have found one issue in older iOS Safaris. There is a black bar on the right and the left with `height: auto` that isn't there without it. But I think it's only a minor issue and is no blocker.

auto-height-video-ios7-ipad

**Pull request merged**
