### PR TITLE
Exclude namespace in page look-ups

### PR DESCRIPTION
**Pull request by Klap-in**
Enables excluding namespaces in the quick search of the searchform
Supports quick search in https://github.com/Klap-in/dokuwiki-plugin-searchform/issues/7

### CODE REVIEW

**Comment by Klap-in** [comment]
intellij IDEA complains about the naming convention. Should file/class name be changed yet?

**Comment by splitbrain** [comment]
@Klap-in which class does it complain about?

**Comment by Klap-in** [comment]
About ‘FulltextPageLookupTest’ that it does not align with PSR.

**Comment by splitbrain** [comment]
Ah I see. For now we ignore PSR formatting problems for the tests.

**Pull request merged**
