### PR TITLE
Corrected internal link pattern to properly handle included square brackets.

### LINKED ISSUE #829: Sequence of closing square brackets might extend link
As reported in https://forum.dokuwiki.org/post/44966, a sequence of three or more closing square brackets causes a link to extend to that point if the link text contains an opening square bracket. Test case:

```
[[https://www.dokuwiki.org/faq:support|[DokuWiki] Support]]

<code>
command [arg1 [arg2 [arg3]]]
</code>
```

Tested in Adora Bell, Binky and Ponder Stibbons.

### PR DESCRIPTION
**Pull request by LarsGit223**
Fixes #829.

From #1609 I took the sugested pattern:
```
\[\[.+?\]\](?!\])
```
But this failed the test ```testInternalLinkNoChar()```. So I corrected it to:
```
\[\[.*?\]\](?!\])
```
I also added test code.

### CODE REVIEW

**Comment by j0hannes** [comment]
This topic is stuck for three months now. Since checks have passed I assume it's save to manually apply changes to `parser.php`?

**Comment by LarsGit223** [comment]
Should be. As you see I have added test code and that did run through without problems. Please report your results.

@splitbrain: Hi. It would be nice if you find the time to check/merge this.

**Comment by j0hannes** [comment]
I works as expected now. I hope nobody performs an update before it gets merged.

**Comment by LarsGit223** [comment]
Thanks for the feedback.

**Comment by splitbrain** [comment]
Seems to work fine. Thanks!

**Comment by LarsGit223** [comment]
Thanks for merging.

**Pull request merged**
