### PR TITLE
move IXR XML RPC to composer dependency #1970

### PR DESCRIPTION
**Pull request by splitbrain**
This is a monky patched version of kissyfrot/php-ixr until my PR has
been accepted upstream.

Plugins using the XML RPC client may need adjustments.

### CODE REVIEW

**Comment by turnermm** [comment]
> Plugins using the XML RPC client may need adjustments.

What kind of adjustments?

**Comment by splitbrain** [comment]
The client is now namespaced `\dokuwiki\Remote\IXR\Client` and no longer inherits from HTTPClient but from the original IXR Client.

**Comment by turnermm** [comment]
It's no longer possible to set the debug parameter, as shown in the demos:
   https://www.dokuwiki.org/devel:xmlrpc:clients
It throws one of two errors, depending on whether you use the setDebug method or set the property directly using $client->debug.  
```
Error: Call to undefined method dokuwiki\Remote\IXR\Client::setDebug()
Error: Cannot access protected property dokuwiki\Remote\IXR\Client::$debug
```
It turns out that the debug value was a function of HTTPClient.

**Comment by splitbrain** [comment]
docs will need to be adjusted. you can call getHttpClient() and set debugging on that

**Comment by turnermm** [comment]
Thanks.  Works perfectly.  I'll update the docs.

**Comment by turnermm** [comment]
But I'll wait until the new code is merged.

**Comment by Klap-in** [comment]
@turnermm Do you have the opportunity to update the docs? If you are done, could you remove the label please?

**Comment by turnermm** [comment]
Docs have been updated 
https://www.dokuwiki.org/devel:xmlrpc:clients#sample_php_client

**Comment by turnermm** [comment]
Ah, I see you not splitbrain added the tlo-do label

**Comment by Klap-in** [comment]
Thanks!

**Pull request merged**
