### PR TITLE
Optimize Lexer state stack

### PR DESCRIPTION
**Pull request by zither**

### CODE REVIEW

**Comment by Chris--S** [comment]
The lexer is pretty important to the first stage of page parsing.  Can you run a couple of tests to double check this change has negligible impact on:
- speed of generating instructions
- memory usage.

I use the content of https://www.dokuwiki.org/devel:parser for my parser checks.  Its one of the toughest pages in dokuwiki.org.  Just paste its contents into your test wiki and make a few before and after runs.  Post execution time and memory usage stats back here.

**Comment by Chris--S** [comment]
@zither how come you closed this?  I like the code changes, they are sensible and start to modernise the lexer's PHP.  We just need to verify they won't have any negative impact on performance.  If you need help doing the benchmarking please say.

**Comment by zither** [comment]
Sorry, I have tested it, a bit slower, actually.

**Comment by Chris--S** [comment]
@zither - there is no rush - any chance you can post the times you saw so we can judge how significant it is.  Thanks.

**Comment by zither** [comment]
I just made two simple tests: https://gist.github.com/zither/668ce48e01f916c6de02

The splstack is a bit slower than the original stack, and no memory usage improvement in normal case.

test1_speed_test:
```
// original stack
Start time index: 0.0010590553283691
End time index:   8.2340710163116
taken:            8.2330119609833

// splstack
Start time index: 0.0010709762573242
End time index:   8.5719630718231
taken:            8.5708920955658
```

test1_memory_test:
```
// original stack
Start memory usage: 182160
End memory usage:   4377044
Peak:               76379776

// splstack
Start memory usage: 182736
End memory usage:   183404
Peak:               52185516
```

test2_speed_test:
```
// original stack
Start time index: 0.062956094741821
End time index:   0.60582113265991
taken:            0.54286503791809

// splstack
Start time index: 0.063015937805176
End time index:   0.6052508354187
taken:            0.54223489761353
```

test2_memory_test:
```
// original stack
Start memory usage: 3996612
End memory usage:   5603356
Peak:               6347120


//splstack
Start memory usage: 3997268
End memory usage:   5604524
Peak:               6348468

**Pull request closed without merging**
