### PR TITLE
PHP 7.4 support for CI

### PR DESCRIPTION
**Pull request by phy25**
This is a work-in-progress for PHP 7.4 support.

- [x] Add PHP `7.4snapshot` test to Travis CI (7.4 is not ready on Travis CI yet)
- [x] Remove PHP 7.0 and 7.1 from travis and appveyor tests
- [ ] Upgrade MarcusSchwarz/lesserphp (I have MarcusSchwarz/lesserphp#16, since I don't want to monkey-patch immediately)
- [ ] monkey-patching for #2406 (MarcusSchwarz/lesserphp#17 (comment)) - not going to do this one in this PR

### CODE REVIEW

**Comment by splitbrain** [comment]
What's the status here? MarcusSchwarz/lesserphp#16 seems to be merged, so I guess we can simply upgrade the dependency and merge this PR?

**Comment by phy25** [comment]
I need to double check to see if Travis CI has official PHP 7.4 support now - shouldn't take too long.

**Comment by phy25** [comment]
Pending https://github.com/MarcusSchwarz/lesserphp/issues/17#issuecomment-576062732, and also potential monkey-patching for #2406 (https://github.com/MarcusSchwarz/lesserphp/issues/17#issuecomment-576038689).

**Comment by phy25** [comment]
Failing tests :-(. Now pending MarcusSchwarz/lesserphp#18.

**Comment by phy25** [comment]
I just read our changelog, which claims that we have support for PHP 7.4, while this is still pending. Do we want to just monkey-patch MarcusSchwarz/lesserphp#16 before waiting for an upstream release?

**Comment by splitbrain** [comment]
Yes we should monkey patch for now. Can you do it and update the CI setup?

We should also have a new ticket to keep track of the monkey patch and upstream status.

**Pull request closed without merging**
