### PR TITLE
fileicons: allow specify what sizes to dump

### PR DESCRIPTION
**Pull request by glensc**
this way i could show only 16px icons on webpage:

```html
===== Available File Icons =====

Available ''16x16'' icons:

<html>
<iframe src="/lib/images/fileicons/?size=16" style="border-width:0" width="450" height="190" frameborder="0" scrolling="no"></iframe>
</html>
```

### CODE REVIEW

**Comment by glensc** [comment]
hmm, seems dokuwiki cuts out "src" attribute from iframe, if i add "?" to it's url:

```
<iframe src="/lib/images/fileicons/?size=16">
```

results `<iframe>` without `src` attribute in browser inspection

screenshot-1

**Comment by Klap-in** [comment]
Is this worth inclusion in DokuWiki? I don't see an use case for other users? Is there any use case?
Why don't you duplicate this script in the image folder? that is update save as well.

Where does DokuWiki filter html included in `<html>` tags? It is not a browser functionality?

**Comment by Klap-in** [comment]
What happens if you don't show the preview, but show it in an saved page?

**Comment by splitbrain** [comment]
Yeah, I don't see much sense in this either. I consider the index.php for the icons more like a gimmik than a feature and I would rather not increase complexity here.

**Pull request closed without merging**
