### PR TITLE
Translation update (cs)

### PR DESCRIPTION
**Pull request by dokuwiki-translate**
This pull request contains some translation updates.

### CODE REVIEW

**Comment by gorn** [comment]
What is the role of reviewer? Sorry, but I am not familiar with this :)

**Comment by Klap-in** [comment]
You have the possibility to have a look in the changed files of this pull request, and provide comments if you observe content that needs to be improved. So that people's that has the ability to perform the merge got capable advice from someone with experience with the language :-)

**Comment by krivka** [comment]
Klap-in: Thank you for the explanation. I did not understand the emails about the pull requests as well, since I have no rights to approve them. I looked on the changes and they are all valid improvements of Czech translation or corrections of typos, so I hope "closed requests" mean that they were accepted.

**Comment by phy25** [comment]
Only when they are "merged" or closed via commits, they mean to be accepted to the main codebase. On this case, yes.

**Pull request closed without merging**
