### PR TITLE
Fix PHP 7.3 compatibility issues part1

### PR DESCRIPTION
**Pull request by syntaxseed**
Issues Identified By PHP Code Sniffer:
phpcs --standard=PHPCompatibility --extensions=php,inc,lib --runtime-set testVersion 7.3- .

Issues Fixed:

- Passing the $glue and $pieces parameters in reverse order to join has been deprecated since PHP 7.4; $glue should be the first parameter and $pieces the second.

- PHP has reserved all method names with a double underscore prefix for future use.

(To be continued with PSR2 and Dokuwiki code style rules fixes.)

### CODE REVIEW

**Comment by syntaxseed** [comment]
Hmmm. I will look into the failed tests.

**Comment by syntaxseed** [comment]
Fixed:
- PHPUnit (version 9.3.11) test errors: PHP Fatal error:  Declaration of <class>::<method>() must be compatible with <class>::<method>(): void.

**Comment by syntaxseed** [comment]
The AppVeyor tests are failing on PHP 7.0... but the fix was for 7.3, and I have the latest PHPUnit which doesn't work on 7.0.

I realize this is a small PR in which to figure out this issue... .but time to drop support for unsupported versions of PHP. At least drop the testing. At this point I'm unable to fix this in my environment. I'll leave this hear and start a new branch/PR for some code-style and PSR2 fixes.

**Comment by Klap-in** [comment]
> 
> Note: That was very time consuming. I suspect this is an issue with the particular combo of latest PHP Unit and PHP 7.3.

According to this comment in another project, I understand that you have to follow the way of implementing the phpunit class started using already. https://github.com/spatie/laravel-activitylog/issues/486#issuecomment-481215580

**Comment by Klap-in** [comment]
Looks fine for me (not tested).

**Comment by splitbrain** [comment]
@syntaxseed could you update this PR? Tests have been adjusted for newer phpunit.

**Comment by syntaxseed** [comment]
> @syntaxseed could you update this PR? Tests have been adjusted for newer phpunit.

Will do!

**Comment by syntaxseed** [comment]
I had forgotten about this PR and deleted my fork and I'm not sure how to make changes to this PR now. I will re-fork , fix it up, and issue a new PR.

**Comment by syntaxseed** [comment]
Replaced this PR with a new one ##3536.

**Pull request closed without merging**
