### PR TITLE
Fully remove deprecated each calls

### PR DESCRIPTION
**Pull request by phy25**
The related code in `inc/DifferenceEngine.php` is somewhat complicated, without tests. I am not sure whether I am doing right, and thus maybe someone else can help me check that.

### CODE REVIEW

**Comment by Klap-in** [comment]
Maybe you can just add a simple unit test where you obtain a diff between two versions of a changed article of dokuwiki.org, and check that it uses this function of the diff engine?

**Comment by phy25** [comment]
@Klap-in Yeah that's a good idea, but I am not familiar with this DifferenceEngine yet, and we have to find a fully-covered test case. I don't know, maybe I will work on this some day later.

**Comment by Klap-in** [comment]
in html_diff() (in inc/html.php) the Diff object is used, which calls indirect the class you modified. So I guess that if you use the Diff object in an unit test you can set up a simple test case.
https://github.com/splitbrain/dokuwiki/blob/master/inc/html.php#L1333

**Comment by phy25** [comment]
Test added and it looks good. Thank you @Klap-in.

**Comment by splitbrain** [comment]
looks good to me

**Pull request merged**
