### PR TITLE
Adding auto ajax preview to editing

### PR DESCRIPTION
**Pull request by jthoenes**
Hello Andi,

thank you for your work of dokuwiki - we are really enjoying it!

We did a little extension to automatically render the preview via the ajax request which is issued by the locktimer. The feature is configurable in ACP and is switched off by default.

Kind regards
Lukasz Burdzanowski
Johannes Thönes

### CODE REVIEW

**Comment by AndreWin** [comment]
Hello!
Please help me to understand: I see that there was some patches that allowed to turn on autopreview on dokuwiki. For example in conf/dokuwiki.php was:
```
+$conf['autopreview'] = 0;                //automatically renders preview of the current edited text (0|1)
```
I don't see these patches in the latest code of dokuwiki. Why?

**Comment by Klap-in** [comment]
It is, maybe accidently, closed by @selfthinker at 6 February 2012 from a not related commit....

Reopen?

**Comment by Klap-in** [comment]
Edit: I see note of @splitbrain about closing it. Better implement this as plugin. Therefore it is never merged.

**Comment by AndreWin** [comment]
Yes, reopen this ticket please.

**Comment by AndreWin** [comment]
I didn't find plugin for live preview....

**Comment by AndreWin** [comment]
I'm working on system based on dokuwiki in which engineers can write algoritms for technical calculations. Not all enginners works on comuper well. So live preview (feature of plugin) will make their work much more easier.

**Comment by Klap-in** [comment]
More recent discussion is in this issue: #815

**Comment by Klap-in** [comment]
Maybe there is a little bit overlap with https://www.freelists.org/post/dokuwiki/UI-for-editing-the-active-templates-styleini

**Pull request closed without merging**
