### PR TITLE
Implemented interwiki substitution for external images (issue #1614).

### PR DESCRIPTION
**Pull request by dmak**
See issue #1614 for comments.

### CODE REVIEW

**Comment by dmak** [comment]
Hold on with code review. I just thought that the check `strpos($src, '>')` should be more strict, as it perhaps breaks the case `{{http://foor.com...>...}}`. I will implement better solution shortly.

**Comment by Klap-in** [comment]
The internallink handler could be helpfull: https://github.com/splitbrain/dokuwiki/blob/master/inc/parser/handler.php#L449

**Comment by dmak** [comment]
@Klap-in: Thanks for the link. I have made necessary changes. The feature is ready for review.

**Comment by splitbrain** [comment]
merged. thanks for the PR and the patience while waiting for review

**Pull request merged**
